# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
## set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-fahrenheit false
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -s default-terminal 'tmux-256color'

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

set-option -g destroy-unattached on

set -g prefix C-space
unbind-key C-b
bind-key C-space send-prefix

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Automatically set window title based on session name
set-option -g set-titles on
set-option -g set-titles-string "#S: #W"

# Update pane title based on current command
set-option -g automatic-rename on

run '~/.config/tmux/plugins/tpm/tpm'

bind-key C-Tab next-window
bind-key C-S-Tab previous-window
